---
title: "Merge peptide and protein data"
author: "Colin Wu and Daniel Montemayor"
date: "8/6/2019"
output: html_document
---


# 1) upload 3 files
```{r}
# Read CSV into R
Peptides <- read.csv(file="anything.csv", header=TRUE, sep=",")
Proteins <- read.csv(file="anything2.csv", header=TRUE, sep=",")
Import <- read.csv(file="import.csv", header=TRUE, sep=",")
```


# 2) Combine peptide and protein files
```{r}
  merged.data <- merge(Peptides, Proteins, by="record_id")


```
# 3) make column names the same
```{r}
x <- names(Import)
x <- substring(x, 3)
x <- substring(x,1,nchar(x)-6)
x <- toupper(x)
names(Import)<-x
names(Import)[1]<-"record_id"

```
make merged data names the same as import
```{r}
x <- names(merged.data)
x <- substring(x,1,nchar(x)-9)
x <- gsub('\\.', '_', x)
names(merged.data)<-x
names(merged.data)[1]<-"record_id"
```

test column names are the same
```{r}
tf <- names(Import)%in%names(merged.data)

names(Import)[!tf]
#names(merged.data)[!tf]
```



# 4) merge import and merged.data
```{r}

ia <- match(merged.data$record_id,Import$record_id)
ja <- match(names(merged.data),names(Import))

#loop over rows in merged.data
#for(ib in 1:nrow(merged.data) ){
for(ib in 1:3 ){
  print("++++++++++")
  print(ib)
  print(merged.data$record_id[ib])

  #loop over columns in merged.data
  #for(jb in 1:ncol(merged.data)){
  for(jb in 1:3){

    print("----------")
    print(jb)
    print(merged.data[ib,jb])
    print(Import[ia[ib],ja[jb]])


    Import[ia[ib],ja[jb]]<-merged.data[ib,jb]
  }
}



```

```{r}
#finaldata <- merge(Import,merged.data, by=names(merged.data),


```
# 5) save the import file.
```{r}
#write.csv(finaldata,file="finaldata.csv")
```
